### ISSUE TITLE
Error: "key" is missing or undefined

### ISSUE THREAD

**Issue by Jubs210** [GroovyGab/lavalink-music-bot#115]
I followed all steps in setting up the bot. However when I get to the last step running the command `node dist/index.js` I get the following error message:

`Error: "key" is missing or undefined
    at new Statcord (/home/user/Bots/lavalink-music-bot/node_modules/statcord.js/src/Statcord.js:21:25)
    at new MusicBotClient (/home/user/Bots/lavalink-music-bot/dist/structures/Client.js:30:25)
    at Object.<anonymous> (/home/user/Bots/lavalink-music-bot/dist/index.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.4.0`

**Comment by bsjones64667** [comment]
Also getting this same error. Using Node.js v16.6.2

**Comment by iliveinsideyourwalls** [comment]
Ah, my bad. Statcord it's a stats dashboard that I use on my "prod" bot, maybe I pushed that system to this repo by accident, I will fix it when I get home :)

**Comment by iliveinsideyourwalls** [comment]
Meanwhile, you can remove statcord by running:
`npm rm statcord.js`

And removing this block on `src/structures/Client.ts:line29`

```ts
this.statcord = new StatcordClient({
			key: process.env['STATCORD_KEY']!,
			client: this,
			postCpuStatistics: true,
			postMemStatistics: true,
			postNetworkStatistics: true
		});```

**Comment by iliveinsideyourwalls** [comment]
If you have any more issues let me know

**Comment by Jubs210** [comment]
Your suggestions fixed the issue!

**Comment by GroovyGab** [comment]
I'm now going to close this issue as it was fixed [here](https://github.com/GroovyGab/lavalink-music-bot/commit/b583484d3a14ef83aef688bee2e058aa7ccfd42d)
